"use client"

import "@/styles/globals.css"
// import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@material-tailwind/react"
import AOS from "aos"
import "aos/dist/aos.css"
import React from "react"
import Navbar from "@/components/layout/navbar"
// import ScrollBtn from "@/components/scoll-btn/indx"
import { Provider } from "react-redux"
import { store } from "@/redux/store"
import { Toaster } from "sonner"
import Footer from "@/components/layout/footer"
import "swiper/swiper-bundle.css";
const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  React.useEffect(() => {
    AOS.init({
      duration: 1000, // animatsiya davomiyligi (ms)
      offset: 200, // animatsiya boshlanishi uchun oraliq (px)
      easing: "ease-in-out", // animatsiya o'tkazilishi
    })
  }, [])
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <ThemeProvider>
            <div className="grid gap-y-[100px] md:gap-y-[80px] sm:gap-y-[40px]">
              <Navbar />
              <Toaster position="top-right" />
              {children}
              <Footer />
            </div>
            {/* <ScrollBtn /> */}
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  )
}
